# Generated by Django 3.0.4 on 2020-04-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0002_auto_20200420_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newusermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='newusermodel',
            name='last_name',
        ),
    ]
