# Generated by Django 3.0.4 on 2020-04-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0006_auto_20200422_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
