# Generated by Django 3.0.4 on 2020-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0009_auto_20200424_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='hmt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
