# Generated by Django 3.0.4 on 2020-04-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0010_medicine_hmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='take_start',
            field=models.DateField(),
        ),
    ]
