# Generated by Django 3.0.4 on 2020-04-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0015_auto_20200424_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
