# Generated by Django 3.0.4 on 2020-04-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0016_medicine_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='freq',
        ),
        migrations.AddField(
            model_name='medicine',
            name='freq1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='freq2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='freq3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='freq4',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
