# Generated by Django 3.0.4 on 2020-04-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0017_auto_20200424_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='image_url',
            field=models.ImageField(null=True, upload_to='static/static_dirs/images/'),
        ),
    ]
