# Generated by Django 3.0.4 on 2020-04-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0018_neighbor_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='medicine_id',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='MedNoti.Medicine'),
            preserve_default=False,
        ),
    ]
