# Generated by Django 3.0.4 on 2020-04-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0019_neighbor_medicine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='medicine_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedNoti.Medicine'),
        ),
    ]
