# Generated by Django 3.0.4 on 2020-04-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0020_auto_20200425_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbor',
            name='medicine_id',
        ),
        migrations.AddField(
            model_name='medicine',
            name='neighbor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedNoti.Neighbor'),
        ),
    ]
