# Generated by Django 3.0.4 on 2020-04-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0023_medicine_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
