# Generated by Django 3.0.4 on 2020-04-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0024_auto_20200425_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='unit_eat',
            field=models.IntegerField(),
        ),
    ]
