# Generated by Django 3.0.4 on 2020-04-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0025_auto_20200426_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='start_time',
        ),
    ]
