# Generated by Django 3.0.4 on 2020-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0026_auto_20200426_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='taketime',
        ),
        migrations.AddField(
            model_name='schedule',
            name='check1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='check2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='check3',
            field=models.BooleanField(default=False),
        ),
    ]
