# Generated by Django 3.0.4 on 2020-04-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0027_auto_20200426_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='check4',
            field=models.BooleanField(default=False),
        ),
    ]
