# Generated by Django 3.0.4 on 2020-04-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0028_schedule_check4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='forweek',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='result',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
