# Generated by Django 3.0.4 on 2020-04-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedNoti', '0030_schedule_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
